# brief.ps1 -- focus-lens CLI
# Requires: $env:ANTHROPIC_API_KEY set
#
# Usage:
#   .\brief.ps1 -Topic "quantum computing" -Minutes 15 -Context "SWE, no physics"
#   .\brief.ps1                                  # interactive prompts
#   .\brief.ps1 -Save                            # also save brief to creations/

[CmdletBinding()]
param(
    [string]$Topic = "",
    [int]$Minutes = 0,
    [string]$Context = "",
    [string]$Model = "claude-opus-4-7",
    [int]$MaxTokens = 4096,
    [switch]$Save
)

if (-not $env:ANTHROPIC_API_KEY) {
    Write-Host "ANTHROPIC_API_KEY not set." -ForegroundColor Red
    Write-Host "  Set with:  `$env:ANTHROPIC_API_KEY = 'sk-ant-...'  (this session)" -ForegroundColor DarkGray
    Write-Host "  Or persist:  setx ANTHROPIC_API_KEY 'sk-ant-...'  (then reopen shell)" -ForegroundColor DarkGray
    Write-Host "  Alternatively: open prompt.md, fill placeholders, paste into any Claude session (free)." -ForegroundColor DarkGray
    exit 1
}

if (-not $Topic)   { $Topic   = Read-Host "Topic" }
if (-not $Minutes) { $Minutes = [int](Read-Host "Minutes") }
if (-not $Context) { $Context = Read-Host "Your context (what you already know, why you're asking)" }

$promptPath = Join-Path $PSScriptRoot "prompt.md"
if (-not (Test-Path $promptPath)) {
    Write-Host "prompt.md missing next to brief.ps1" -ForegroundColor Red
    exit 1
}
$template = Get-Content $promptPath -Raw -Encoding UTF8
$body = ($template -split '(?m)^---\s*$', 2)[1].Trim()
$prompt = $body.
    Replace('{{TOPIC}}',   $Topic).
    Replace('{{MINUTES}}', "$Minutes").
    Replace('{{CONTEXT}}', $Context)

$payload = @{
    model      = $Model
    max_tokens = $MaxTokens
    messages   = @(@{ role = "user"; content = $prompt })
} | ConvertTo-Json -Depth 10 -Compress

$headers = @{
    "x-api-key"         = $env:ANTHROPIC_API_KEY
    "anthropic-version" = "2023-06-01"
    "content-type"      = "application/json"
}

Write-Host "" -NoNewline
Write-Host "  focusing on: " -NoNewline -ForegroundColor DarkGray
Write-Host "$Topic ($Minutes min)" -ForegroundColor Cyan
Write-Host ""

try {
    $resp = Invoke-RestMethod -Uri "https://api.anthropic.com/v1/messages" -Method POST -Headers $headers -Body $payload
} catch {
    Write-Host "API call failed: $_" -ForegroundColor Red
    exit 1
}

$text = $resp.content[0].text
Write-Output $text

if ($Save) {
    $stamp = Get-Date -Format "yyyy-MM-dd-HHmm"
    $slug  = ($Topic -replace '[^\w\-]+','-').Trim('-').ToLower()
    $outPath = "D:\Claude\creations\$stamp-brief-$slug.md"
    $header = @"
# brief: $Topic

_$Minutes min budget. Context: $Context_

---

$text

---

_generated by brief.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')_
"@
    Set-Content -Path $outPath -Value $header -Encoding UTF8
    Write-Host ""
    Write-Host "  saved: $outPath" -ForegroundColor DarkGray
}
