# steelman.ps1 -- strongest-version CLI
# Requires: $env:ANTHROPIC_API_KEY
#
# Usage:
#   .\steelman.ps1 -View "AI will end creative work" -MyObjection "It augments, doesn't replace"
#   .\steelman.ps1                                # interactive
#   .\steelman.ps1 -Save                          # also save to creations\

[CmdletBinding()]
param(
    [string]$View        = "",
    [string]$MyObjection = "",
    [string]$Model       = "claude-opus-4-7",
    [int]   $MaxTokens   = 2048,
    [switch]$Save
)

if (-not $env:ANTHROPIC_API_KEY) {
    Write-Host "ANTHROPIC_API_KEY not set." -ForegroundColor Red
    Write-Host "  Free path: open prompt.md, fill placeholders, paste into any Claude session." -ForegroundColor DarkGray
    exit 1
}

if (-not $View)        { $View        = Read-Host "View to steelman (one line, or paste below and press Enter twice)" }
if (-not $MyObjection) { $MyObjection = Read-Host "Why you think it's wrong (optional, press Enter to skip)" }
if (-not $MyObjection) { $MyObjection = "(no specific objection provided)" }

$promptPath = Join-Path $PSScriptRoot "prompt.md"
$template = Get-Content $promptPath -Raw -Encoding UTF8
$body = ($template -split '(?m)^---\s*$', 2)[1].Trim()
$prompt = $body.
    Replace('{{VIEW}}',         $View).
    Replace('{{MY_OBJECTION}}', $MyObjection)

$payload = @{
    model      = $Model
    max_tokens = $MaxTokens
    messages   = @(@{ role = "user"; content = $prompt })
} | ConvertTo-Json -Depth 10 -Compress

$headers = @{
    "x-api-key"         = $env:ANTHROPIC_API_KEY
    "anthropic-version" = "2023-06-01"
    "content-type"      = "application/json"
}

Write-Host ""
Write-Host "  building the steelman..." -ForegroundColor DarkGray
Write-Host ""

try {
    $resp = Invoke-RestMethod -Uri "https://api.anthropic.com/v1/messages" -Method POST -Headers $headers -Body $payload
} catch {
    Write-Host "API call failed: $_" -ForegroundColor Red
    exit 1
}

$text = $resp.content[0].text
Write-Output $text

if ($Save) {
    $stamp = Get-Date -Format "yyyy-MM-dd-HHmm"
    $words = ($View -split '\s+') | Select-Object -First 6
    $slug = (($words -join '-') -replace '[^\w\-]+','-').Trim('-').ToLower()
    if (-not $slug) { $slug = "view" }
    $outPath = "D:\Claude\creations\$stamp-steelman-$slug.md"
    $header = @"
# steelman: $View

_My objection: $MyObjection_

---

$text

---

_generated by steelman on $(Get-Date -Format 'yyyy-MM-dd HH:mm')_
"@
    Set-Content -Path $outPath -Value $header -Encoding UTF8
    Write-Host ""
    Write-Host "  saved: $outPath" -ForegroundColor DarkGray
}
