# eat-what-you-have.ps1 -- kitchen-lens CLI
# Requires: $env:ANTHROPIC_API_KEY
#
# Usage:
#   .\eat-what-you-have.ps1 -Items "cabbage, eggs, rice" -Constraints "veg, 20min, 2p"
#   .\eat-what-you-have.ps1                              # interactive
#   .\eat-what-you-have.ps1 -Save                        # also save to creations\

[CmdletBinding()]
param(
    [string]$Items       = "",
    [string]$Constraints = "",
    [string]$Mood        = "",
    [string]$Model       = "claude-opus-4-7",
    [int]   $MaxTokens   = 2048,
    [switch]$Save
)

if (-not $env:ANTHROPIC_API_KEY) {
    Write-Host "ANTHROPIC_API_KEY not set." -ForegroundColor Red
    Write-Host "  Free path: open prompt.md, fill placeholders, paste into any Claude session." -ForegroundColor DarkGray
    exit 1
}

if (-not $Items)       { $Items       = Read-Host "On hand (comma-separated)" }
if (-not $Constraints) { $Constraints = Read-Host "Constraints (diet/time/people)" }
if (-not $Mood)        { $Mood        = Read-Host "Mood (optional, press Enter to skip)" }
if (-not $Mood)        { $Mood        = "no preference" }

$promptPath = Join-Path $PSScriptRoot "prompt.md"
$template = Get-Content $promptPath -Raw -Encoding UTF8
$body = ($template -split '(?m)^---\s*$', 2)[1].Trim()
$prompt = $body.
    Replace('{{ITEMS}}',       $Items).
    Replace('{{CONSTRAINTS}}', $Constraints).
    Replace('{{MOOD}}',        $Mood)

$payload = @{
    model      = $Model
    max_tokens = $MaxTokens
    messages   = @(@{ role = "user"; content = $prompt })
} | ConvertTo-Json -Depth 10 -Compress

$headers = @{
    "x-api-key"         = $env:ANTHROPIC_API_KEY
    "anthropic-version" = "2023-06-01"
    "content-type"      = "application/json"
}

Write-Host ""
Write-Host "  looking in the kitchen..." -ForegroundColor DarkGray
Write-Host ""

try {
    $resp = Invoke-RestMethod -Uri "https://api.anthropic.com/v1/messages" -Method POST -Headers $headers -Body $payload
} catch {
    Write-Host "API call failed: $_" -ForegroundColor Red
    exit 1
}

$text = $resp.content[0].text
Write-Output $text

if ($Save) {
    $stamp = Get-Date -Format "yyyy-MM-dd-HHmm"
    $slug = ((($Items -split ',')[0..1] -join '-') -replace '[^\w\-]+','-').Trim('-').ToLower()
    if (-not $slug) { $slug = "meal" }
    $outPath = "D:\Claude\creations\$stamp-eat-$slug.md"
    $header = @"
# eat: $Items

_Constraints: $Constraints. Mood: $Mood._

---

$text

---

_generated by eat-what-you-have on $(Get-Date -Format 'yyyy-MM-dd HH:mm')_
"@
    Set-Content -Path $outPath -Value $header -Encoding UTF8
    Write-Host ""
    Write-Host "  saved: $outPath" -ForegroundColor DarkGray
}
