# build-your-own-gadget.ps1 -- meta-gadget CLI
# Requires: $env:ANTHROPIC_API_KEY
#
# Usage:
#   .\build-your-own-gadget.ps1 -Pain "I keep forgetting to follow up" -Context "not a coder"
#   .\build-your-own-gadget.ps1                              # interactive
#   .\build-your-own-gadget.ps1 -Save                        # also save to creations\

[CmdletBinding()]
param(
    [string]$Pain      = "",
    [string]$Context   = "",
    [string]$Model     = "claude-opus-4-7",
    [int]   $MaxTokens = 4096,
    [switch]$Save
)

if (-not $env:ANTHROPIC_API_KEY) {
    Write-Host "ANTHROPIC_API_KEY not set." -ForegroundColor Red
    Write-Host "  Free path: open prompt.md, fill placeholders, paste into any Claude session." -ForegroundColor DarkGray
    exit 1
}

if (-not $Pain)    { $Pain    = Read-Host "What's the pain (free text)" }
if (-not $Context) { $Context = Read-Host "Your context (tech level, time, tools)" }

$promptPath = Join-Path $PSScriptRoot "prompt.md"
$template = Get-Content $promptPath -Raw -Encoding UTF8
$body = ($template -split '(?m)^---\s*$', 2)[1].Trim()
$prompt = $body.
    Replace('{{PAIN}}',    $Pain).
    Replace('{{CONTEXT}}', $Context)

$payload = @{
    model      = $Model
    max_tokens = $MaxTokens
    messages   = @(@{ role = "user"; content = $prompt })
} | ConvertTo-Json -Depth 10 -Compress

$headers = @{
    "x-api-key"         = $env:ANTHROPIC_API_KEY
    "anthropic-version" = "2023-06-01"
    "content-type"      = "application/json"
}

Write-Host ""
Write-Host "  designing the gadget..." -ForegroundColor DarkGray
Write-Host ""

try {
    $resp = Invoke-RestMethod -Uri "https://api.anthropic.com/v1/messages" -Method POST -Headers $headers -Body $payload
} catch {
    Write-Host "API call failed: $_" -ForegroundColor Red
    exit 1
}

$text = $resp.content[0].text
Write-Output $text

if ($Save) {
    $stamp = Get-Date -Format "yyyy-MM-dd-HHmm"
    $words = ($Pain -split '\s+') | Select-Object -First 6
    $slug = (($words -join '-') -replace '[^\w\-]+','-').Trim('-').ToLower()
    if (-not $slug) { $slug = "gadget" }
    $outPath = "D:\Claude\creations\$stamp-bygadget-$slug.md"
    $header = @"
# bygadget: $Pain

_Context: $Context_

---

$text

---

_generated by build-your-own-gadget on $(Get-Date -Format 'yyyy-MM-dd HH:mm')_
"@
    Set-Content -Path $outPath -Value $header -Encoding UTF8
    Write-Host ""
    Write-Host "  saved: $outPath" -ForegroundColor DarkGray
}
